In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

In [2]:
def calc_sec(time):
    hms = time.split(':')
    hms = [float(x) for x in hms]
    sec = hms[2] + hms[1]*60 + hms[0]*3600
    sec = round(sec,3)
    return sec

In [3]:
def calc_ts(sec):
    ts = ''
    hr = int(sec/3600)
    mn = int((sec - (hr*3600))/60)
    sc = sec - (hr*3600) - (mn*60)
    sc = round(sc,3)
    ts += str(hr) + ':' + str(mn) + ':' + str(sc)
    # print(ts)
    return ts

In [4]:
def calc_t_period(dates,secs):
    t_period = []
    
    start_sec = secs[0]
    prev_sec = secs[0]
    prev_date = dates[0]

    for i in range(len(secs)):
        curr_sec = secs[i]
        diff_sec = curr_sec - prev_sec
        curr_date = dates[i]
        
        if((diff_sec>3.0) and (curr_date==prev_date)):
            t_period.append([curr_date,start_sec,prev_sec])
            start_sec = curr_sec
        elif(curr_date!=prev_date):
            t_period.append([prev_date,start_sec,prev_sec])
            start_sec = curr_sec
            prev_date = curr_date
        elif(i==len(secs)-1):
            t_period.append([curr_date,start_sec,curr_sec])

        prev_sec = curr_sec
    
    return t_period

In [5]:
def equation_bai(X_i):
    all_std = []
    
    std_i = np.std(X_i,axis=0)
    diff_std = std_i**2 - std_i_bar**2
    diff_std = (diff_std + 1) / (std_i_bar**2 + 1)
    
    diff_std_ = std_i**2

    all_std.append(diff_std)
    
    all_std = np.array(all_std)
    
    ai = np.sum(all_std**2,axis=1)/3
    ai[ai<0] = 0
    ai = np.sqrt(ai)
    
    return ai

In [6]:
std_i_bar = [0.00349329,0.00465817,0.00543154]
std_i_bar = np.array(std_i_bar)

## Import Data in Certain Time Period

In [7]:
subject_name = 'pond'

if(subject_name=='ped'):
    rec_date = '2019-01-04'
    start_time = '11:37:01'
    end_time = '11:42:13'

if(subject_name=='pond'):
    rec_date = '2016-01-01'
    start_time = '07:42:14'
    end_time = '07:47:01'

if(subject_name=='indy'):
    rec_date = '2018-12-19'
    start_time = '16:17:05'
    end_time = '16:21:55'

In [8]:
datapath = 'SmartwatchData/raw_data/'

filepath = datapath + 'log_acc_' + subject_name + '.csv'
df = pd.read_csv(filepath)
filtered = [i for i in df['timestamp'] if i[:10]==rec_date and calc_sec(i[11:])>calc_sec(start_time) 
            and calc_sec(i[11:])<calc_sec(end_time)]

df_filt = df[df['timestamp'].isin(filtered)]
df_filt = df_filt.reset_index(drop=True)

cols = ['timestamp','x','y','z']
df_filt = df_filt[cols]

df_filt

                    timestamp          x         y         z
0     2016-01-01 07:42:14.087  -3.794810 -2.211045  8.607155
1     2016-01-01 07:42:14.233  -4.551377 -1.914164  8.420407
2     2016-01-01 07:42:14.416  -4.991911 -2.081758  7.759608
3     2016-01-01 07:42:14.556  -6.399701 -1.885434  8.037335
4     2016-01-01 07:42:14.716  -7.271191 -1.282095  6.754043
5     2016-01-01 07:42:14.875  -7.841011 -1.315614  6.351817
6     2016-01-01 07:42:15.046  -7.979874 -1.368286  5.197812
7     2016-01-01 07:42:15.196  -8.458715 -1.593341  4.814740
8     2016-01-01 07:42:15.357  -8.865729 -1.612495  4.484340
9     2016-01-01 07:42:15.517  -9.229648 -2.589329  3.766079
10    2016-01-01 07:42:15.678  -8.688558 -2.249353  2.942474
11     2016-01-01 07:42:15.84  -9.038112 -2.369063  3.090915
12    2016-01-01 07:42:16.016  -8.860941 -2.091335  3.062184
13    2016-01-01 07:42:16.267  -9.411607 -2.297236  3.038242
14    2016-01-01 07:42:16.321  -9.138668 -2.287660  2.813187
15    2016-01-01 07:42:16.482  -9.609129 -3.274071  3.708618
16    2016-01-01 07:42:16.641  -9.815030 -5.170279  4.843470
17    2016-01-01 07:42:16.802  -6.309918 -8.383297  5.288792
18    2016-01-01 07:42:16.963  -1.804031 -8.756793  3.454833
19    2016-01-01 07:42:17.123   4.898537 -5.855020  1.472434
20    2016-01-01 07:42:17.283   4.486734 -4.724957  0.375890
21    2016-01-01 07:42:17.446   6.641516 -6.578069  0.955286
22    2016-01-01 07:42:17.604   7.489063 -4.768053 -0.422577
23    2016-01-01 07:42:17.765   6.780379 -5.476736  1.142034
24    2016-01-01 07:42:17.926   3.816358 -4.025850 -0.571017
25    2016-01-01 07:42:18.086  -1.612495 -8.570044  2.238579
26     2016-01-01 07:42:18.25  -5.898116 -6.578069  3.900155
27    2016-01-01 07:42:18.413 -16.193184 -7.885304  5.887342
28    2016-01-01 07:42:18.592  -9.633071 -1.492785  2.870648
29    2016-01-01 07:42:18.731  -8.752005 -2.713828  2.147599
...                       ...        ...       ...       ...
1757  2016-01-01 07:46:56.076   0.948104  6.818687  7.212533
1758  2016-01-01 07:46:56.241   0.450110  6.588843  6.585252
1759  2016-01-01 07:46:56.395   0.124498  6.526594  6.685808
1760  2016-01-01 07:46:56.559   0.129287  6.646304  6.810307
1761  2016-01-01 07:46:56.718   0.416591  6.603208  6.968324
1762  2016-01-01 07:46:56.877   0.062249  6.110003  6.695385
1763  2016-01-01 07:46:57.037   1.403002  8.164227  7.528567
1764    2016-01-01 07:46:57.2   0.110133  6.694188  6.896498
1765  2016-01-01 07:46:57.359   0.167594  6.842629  6.977901
1766  2016-01-01 07:46:57.521   0.004788  6.756437  6.882133
1767   2016-01-01 07:46:57.68   0.043096  6.627151  6.953959
1768   2016-01-01 07:46:57.84   0.167594  6.770802  6.901287
1769    2016-01-01 07:46:58.0   0.196325  6.847417  7.001843
1770  2016-01-01 07:46:58.163   0.057461  6.670246  6.977901
1771  2016-01-01 07:46:58.322   0.450110  7.192182  6.862979
1772  2016-01-01 07:46:58.485   0.344765  7.005434  6.671443
1773  2016-01-01 07:46:58.643   0.320823  6.789956  6.800730
1774  2016-01-01 07:46:58.805   0.181959  7.024588  6.776788
1775  2016-01-01 07:46:58.964   0.502782  7.158663  7.020997
1776  2016-01-01 07:46:59.139   0.258574  6.928820  6.767211
1777  2016-01-01 07:46:59.285   0.105345  6.895301  6.666655
1778  2016-01-01 07:46:59.445   0.229843  7.010222  6.748057
1779  2016-01-01 07:46:59.646   0.062249  6.885724  6.795941
1780  2016-01-01 07:46:59.768   0.244209  6.746860  6.661866
1781  2016-01-01 07:47:00.079   0.177171  6.828263  6.671443
1782  2016-01-01 07:47:00.145   0.296881  7.144298  6.791153
1783  2016-01-01 07:47:00.248   0.086191  7.024588  6.815095
1784  2016-01-01 07:47:00.409   0.119710  7.149087  6.695385
1785  2016-01-01 07:47:00.571   0.253785  6.943185  6.451177
1786  2016-01-01 07:47:00.729   0.186748  7.091625  6.752846

[1787 rows x 4 columns]

In [9]:
filepath = datapath + 'log_hr_'+ subject_name + '.csv'
df2 = pd.read_csv(filepath)

filtered = [i for i in df2['timestamp'] if i[:10]==rec_date and calc_sec(i[11:])>calc_sec(start_time) 
            and calc_sec(i[11:])<calc_sec(end_time)]

df_hr = df2[df2['timestamp'].isin(filtered)]
df_hr = df_hr.reset_index(drop=True)

cols = ['timestamp','hr']
df_hr = df_hr[cols]

df_hr

                   timestamp         hr
0    2016-01-01 07:42:15.211   0.000000
1    2016-01-01 07:42:16.311   0.000000
2      2016-01-01 07:42:17.4   0.000000
3     2016-01-01 07:42:18.51   0.000000
4     2016-01-01 07:42:19.65   0.000000
5    2016-01-01 07:42:20.732   0.000000
6    2016-01-01 07:42:21.842   0.000000
7    2016-01-01 07:42:22.924   0.000000
8    2016-01-01 07:42:24.057   0.000000
9    2016-01-01 07:42:25.115   0.000000
10    2016-01-01 07:42:26.22   0.000000
11   2016-01-01 07:42:27.311  49.912586
12   2016-01-01 07:42:28.412  49.912586
13   2016-01-01 07:42:29.512  49.912586
14   2016-01-01 07:42:30.604  49.939865
15   2016-01-01 07:42:31.693  51.374302
16   2016-01-01 07:42:32.792  54.199356
17   2016-01-01 07:42:33.894  56.048424
18   2016-01-01 07:42:34.998  57.314920
19   2016-01-01 07:42:36.093  57.948166
20   2016-01-01 07:42:37.173  64.252990
21   2016-01-01 07:42:38.264  68.766190
22    2016-01-01 07:42:39.41  71.022800
23   2016-01-01 07:42:40.514  72.151090
24   2016-01-01 07:42:41.594  71.954510
25     2016-01-01 07:42:42.7  71.346220
26   2016-01-01 07:42:43.798  69.273080
27   2016-01-01 07:42:44.887  68.101520
28   2016-01-01 07:42:45.982  67.447330
29   2016-01-01 07:42:47.096  67.080230
..                       ...        ...
230  2016-01-01 07:46:28.204  52.977406
231  2016-01-01 07:46:29.301  52.730057
232  2016-01-01 07:46:30.383  52.773674
233  2016-01-01 07:46:31.492  52.795486
234  2016-01-01 07:46:32.573  52.806390
235  2016-01-01 07:46:33.673  52.623177
236  2016-01-01 07:46:34.764  52.060562
237  2016-01-01 07:46:35.871  51.724083
238  2016-01-01 07:46:36.963  51.537384
239  2016-01-01 07:46:38.064  51.462494
240  2016-01-01 07:46:39.163  51.425050
241  2016-01-01 07:46:40.254  51.406326
242  2016-01-01 07:46:41.354  51.395493
243  2016-01-01 07:46:42.453  51.390076
244  2016-01-01 07:46:43.543  51.387367
245  2016-01-01 07:46:44.643  51.460655
246  2016-01-01 07:46:45.745  51.961357
247  2016-01-01 07:46:46.833  52.727062
248  2016-01-01 07:46:47.923  53.392914
249  2016-01-01 07:46:49.035  54.172005
250  2016-01-01 07:46:50.125  54.561554
251  2016-01-01 07:46:51.223  54.756325
252  2016-01-01 07:46:52.333  54.688934
253  2016-01-01 07:46:53.422  53.162018
254  2016-01-01 07:46:54.515  52.299934
255  2016-01-01 07:46:55.653  51.685720
256   2016-01-01 07:46:56.74  51.368134
257  2016-01-01 07:46:57.881  51.209343
258  2016-01-01 07:46:58.985  48.801308
259  2016-01-01 07:47:00.161  46.580784

[260 rows x 2 columns]

In [10]:
hr_cnt = 0

for i in range(len(df_filt)):
    hr_time = df_hr.loc[hr_cnt,'timestamp'].split(' ')[1]
    filt_time = df_filt.loc[i,'timestamp'].split(' ')[1]
    
    if(calc_sec(hr_time)<=calc_sec(filt_time)):
        if(hr_cnt<len(df_hr)-1):
            hr_cnt += 1
    df_filt.loc[i,'HR'] = df_hr.loc[hr_cnt,'hr']

In [11]:
df_filt

                    timestamp          x         y         z         HR
0     2016-01-01 07:42:14.087  -3.794810 -2.211045  8.607155   0.000000
1     2016-01-01 07:42:14.233  -4.551377 -1.914164  8.420407   0.000000
2     2016-01-01 07:42:14.416  -4.991911 -2.081758  7.759608   0.000000
3     2016-01-01 07:42:14.556  -6.399701 -1.885434  8.037335   0.000000
4     2016-01-01 07:42:14.716  -7.271191 -1.282095  6.754043   0.000000
5     2016-01-01 07:42:14.875  -7.841011 -1.315614  6.351817   0.000000
6     2016-01-01 07:42:15.046  -7.979874 -1.368286  5.197812   0.000000
7     2016-01-01 07:42:15.196  -8.458715 -1.593341  4.814740   0.000000
8     2016-01-01 07:42:15.357  -8.865729 -1.612495  4.484340   0.000000
9     2016-01-01 07:42:15.517  -9.229648 -2.589329  3.766079   0.000000
10    2016-01-01 07:42:15.678  -8.688558 -2.249353  2.942474   0.000000
11     2016-01-01 07:42:15.84  -9.038112 -2.369063  3.090915   0.000000
12    2016-01-01 07:42:16.016  -8.860941 -2.091335  3.062184   0.000000
13    2016-01-01 07:42:16.267  -9.411607 -2.297236  3.038242   0.000000
14    2016-01-01 07:42:16.321  -9.138668 -2.287660  2.813187   0.000000
15    2016-01-01 07:42:16.482  -9.609129 -3.274071  3.708618   0.000000
16    2016-01-01 07:42:16.641  -9.815030 -5.170279  4.843470   0.000000
17    2016-01-01 07:42:16.802  -6.309918 -8.383297  5.288792   0.000000
18    2016-01-01 07:42:16.963  -1.804031 -8.756793  3.454833   0.000000
19    2016-01-01 07:42:17.123   4.898537 -5.855020  1.472434   0.000000
20    2016-01-01 07:42:17.283   4.486734 -4.724957  0.375890   0.000000
21    2016-01-01 07:42:17.446   6.641516 -6.578069  0.955286   0.000000
22    2016-01-01 07:42:17.604   7.489063 -4.768053 -0.422577   0.000000
23    2016-01-01 07:42:17.765   6.780379 -5.476736  1.142034   0.000000
24    2016-01-01 07:42:17.926   3.816358 -4.025850 -0.571017   0.000000
25    2016-01-01 07:42:18.086  -1.612495 -8.570044  2.238579   0.000000
26     2016-01-01 07:42:18.25  -5.898116 -6.578069  3.900155   0.000000
27    2016-01-01 07:42:18.413 -16.193184 -7.885304  5.887342   0.000000
28    2016-01-01 07:42:18.592  -9.633071 -1.492785  2.870648   0.000000
29    2016-01-01 07:42:18.731  -8.752005 -2.713828  2.147599   0.000000
...                       ...        ...       ...       ...        ...
1757  2016-01-01 07:46:56.076   0.948104  6.818687  7.212533  51.368134
1758  2016-01-01 07:46:56.241   0.450110  6.588843  6.585252  51.368134
1759  2016-01-01 07:46:56.395   0.124498  6.526594  6.685808  51.368134
1760  2016-01-01 07:46:56.559   0.129287  6.646304  6.810307  51.368134
1761  2016-01-01 07:46:56.718   0.416591  6.603208  6.968324  51.368134
1762  2016-01-01 07:46:56.877   0.062249  6.110003  6.695385  51.209343
1763  2016-01-01 07:46:57.037   1.403002  8.164227  7.528567  51.209343
1764    2016-01-01 07:46:57.2   0.110133  6.694188  6.896498  51.209343
1765  2016-01-01 07:46:57.359   0.167594  6.842629  6.977901  51.209343
1766  2016-01-01 07:46:57.521   0.004788  6.756437  6.882133  51.209343
1767   2016-01-01 07:46:57.68   0.043096  6.627151  6.953959  51.209343
1768   2016-01-01 07:46:57.84   0.167594  6.770802  6.901287  51.209343
1769    2016-01-01 07:46:58.0   0.196325  6.847417  7.001843  48.801308
1770  2016-01-01 07:46:58.163   0.057461  6.670246  6.977901  48.801308
1771  2016-01-01 07:46:58.322   0.450110  7.192182  6.862979  48.801308
1772  2016-01-01 07:46:58.485   0.344765  7.005434  6.671443  48.801308
1773  2016-01-01 07:46:58.643   0.320823  6.789956  6.800730  48.801308
1774  2016-01-01 07:46:58.805   0.181959  7.024588  6.776788  48.801308
1775  2016-01-01 07:46:58.964   0.502782  7.158663  7.020997  48.801308
1776  2016-01-01 07:46:59.139   0.258574  6.928820  6.767211  46.580784
1777  2016-01-01 07:46:59.285   0.105345  6.895301  6.666655  46.580784
1778  2016-01-01 07:46:59.445   0.229843  7.010222  6.748057  46.580784
1779  2016-01-01 07:46:59.646   0.062249  6.885724  6.795941  46.580784
1780  2016-01-01 07:46:59.768   0.244209  6.746860  6.661866  46.580784
1781  2016-01-01 07:47:00.079   0.177171  6.828263  6.671443  46.580784
1782  2016-01-01 07:47:00.145   0.296881  7.144298  6.791153  46.580784
1783  2016-01-01 07:47:00.248   0.086191  7.024588  6.815095  46.580784
1784  2016-01-01 07:47:00.409   0.119710  7.149087  6.695385  46.580784
1785  2016-01-01 07:47:00.571   0.253785  6.943185  6.451177  46.580784
1786  2016-01-01 07:47:00.729   0.186748  7.091625  6.752846  46.580784

[1787 rows x 5 columns]

In [12]:
cols = df_filt.columns.tolist()

row_len = len(df_filt.index)

dates = [df_filt.iloc[i,0].split(' ')[0] for i in range(row_len)]
secs = [calc_sec(df_filt.iloc[i,0].split(' ')[1]) for i in range(row_len)]

period = calc_t_period(dates,secs)

ts = []
for elem in period:
    ts.append([elem[0],calc_ts(elem[1]),calc_ts(elem[2])])
    
ts = np.array(ts)
print(ts)

[['2016-01-01' '7:42:14.087' '7:47:0.729']]

In [13]:
ts1 = [i for i in df_filt['timestamp'] if calc_sec(i[11:])<=calc_sec(ts[0][2])]
df1 = df_filt[df_filt['timestamp'].isin(ts1)]

g = 9.8
df1.loc[:,'x'] = df1['x'].apply(lambda x: x/g)
df1.loc[:,'y'] = df1['y'].apply(lambda x: x/g)
df1.loc[:,'z'] = df1['z'].apply(lambda x: x/g)

## Calculate Activity Index

In [14]:
H = 10
ai1 = []

for i in range(len(df1)):
    xyz_val = []
    if(i-H>=0):
        for j in range(H,0,-1):
            xyz_val.append([df1.iloc[i-j,1],df1.iloc[i-j,2],df1.iloc[i-j,3]])
        ai_val = float(equation_bai(xyz_val))
        ai1.append(ai_val)
    else:
        ai1.append(1)

In [15]:
df1['AI'] = pd.Series(ai1)

df1

,timestamp,x,y,z,HR,AI
0,2016-01-01 07:42:14.087,-0.387225,-0.225617,0.878281,0.000000,1.000000
1,2016-01-01 07:42:14.233,-0.464426,-0.195323,0.859225,0.000000,1.000000
2,2016-01-01 07:42:14.416,-0.509379,-0.212424,0.791797,0.000000,1.000000
3,2016-01-01 07:42:14.556,-0.653031,-0.192391,0.820136,0.000000,1.000000
4,2016-01-01 07:42:14.716,-0.741958,-0.130826,0.689188,0.000000,1.000000
5,2016-01-01 07:42:14.875,-0.800103,-0.134246,0.648145,0.000000,1.000000
6,2016-01-01 07:42:15.046,-0.814273,-0.139621,0.530389,0.000000,1.000000
7,2016-01-01 07:42:15.196,-0.863134,-0.162586,0.491300,0.000000,1.000000
8,2016-01-01 07:42:15.357,-0.904666,-0.164540,0.457586,0.000000,1.000000
9,2016-01-01 07:42:15.517,-0.941801,-0.264217,0.384294,0.000000,1.000000
10,2016-01-01 07:42:15.678,-0.886588,-0.229526,0.300252,0.000000,1.021845
11,2016-01-01 07:42:15.84,-0.922256,-0.241741,0.315399,0.000000,1.020067
12,2016-01-01 07:42:16.016,-0.904178,-0.213402,0.312468,0.000000,1.016859
13,2016-01-01 07:42:16.267,-0.960368,-0.234412,0.310025,0.000000,1.012719
14,2016-01-01 07:42:16.321,-0.932517,-0.233435,0.287060,0.000000,1.008433
15,2016-01-01 07:42:16.482,-0.980523,-0.334089,0.378430,0.000000,1.006009
16,2016-01-01 07:42:16.641,-1.001534,-0.527579,0.494232,0.000000,1.003942
17,2016-01-01 07:42:16.802,-0.643869,-0.855438,0.539673,0.000000,1.005850
18,2016-01-01 07:42:16.963,-0.184085,-0.893550,0.352534,0.000000,1.018696
19,2016-01-01 07:42:17.123,0.499851,-0.597451,0.150248,0.000000,1.042305
20,2016-01-01 07:42:17.283,0.457830,-0.482138,0.038356,0.000000,1.099115
21,2016-01-01 07:42:17.446,0.677706,-0.671232,0.097478,0.000000,1.141765
22,2016-01-01 07:42:17.604,0.764190,-0.486536,-0.043120,0.000000,1.187206
23,2016-01-01 07:42:17.765,0.691875,-0.558851,0.116534,0.000000,1.220701
24,2016-01-01 07:42:17.926,0.389424,-0.410801,-0.058267,0.000000,1.220165
25,2016-01-01 07:42:18.086,-0.164540,-0.874494,0.228426,0.000000,1.190178
26,2016-01-01 07:42:18.25,-0.601849,-0.671232,0.397975,0.000000,1.144894
27,2016-01-01 07:42:18.413,-1.652366,-0.804623,0.600749,0.000000,1.113209
28,2016-01-01 07:42:18.592,-0.982966,-0.152325,0.292923,0.000000,1.217313
29,2016-01-01 07:42:18.731,-0.893062,-0.276921,0.219143,0.000000,1.262961
...,...,...,...,...,...,...
1757,2016-01-01 07:46:56.076,0.096745,0.695784,0.735973,51.368134,1.000914
1758,2016-01-01 07:46:56.241,0.045930,0.672331,0.671964,51.368134,1.001314
1759,2016-01-01 07:46:56.395,0.012704,0.665979,0.682225,51.368134,1.001472
1760,2016-01-01 07:46:56.559,0.013193,0.678194,0.694929,51.368134,1.001220
1761,2016-01-01 07:46:56.718,0.042509,0.673797,0.711053,51.368134,1.001001
1762,2016-01-01 07:46:56.877,0.006352,0.623470,0.683203,51.209343,1.001002
1763,2016-01-01 07:46:57.037,0.143163,0.833084,0.768221,51.209343,1.001082
1764,2016-01-01 07:46:57.2,0.011238,0.683080,0.703724,51.209343,1.002498
1765,2016-01-01 07:46:57.359,0.017101,0.698227,0.712031,51.209343,1.001945
1766,2016-01-01 07:46:57.521,0.000489,0.689432,0.702258,51.209343,1.001779
1767,2016-01-01 07:46:57.68,0.004398,0.676240,0.709588,51.209343,1.001723
1768,2016-01-01 07:46:57.84,0.017101,0.690898,0.704213,51.209343,1.001597
1769,2016-01-01 07:46:58.0,0.020033,0.698716,0.714474,48.801308,1.001543
1770,2016-01-01 07:46:58.163,0.005863,0.680637,0.712031,48.801308,1.001492
1771,2016-01-01 07:46:58.322,0.045930,0.733896,0.700304,48.801308,1.001490
1772,2016-01-01 07:46:58.485,0.035180,0.714840,0.680759,48.801308,1.001522
1773,2016-01-01 07:46:58.643,0.032737,0.692853,0.693952,48.801308,1.001291
1774,2016-01-01 07:46:58.805,0.018567,0.716795,0.691509,48.801308,1.000143
1775,2016-01-01 07:46:58.964,0.051304,0.730476,0.716428,48.801308,1.000151
1776,2016-01-01 07:46:59.139,0.026385,0.707022,0.690532,46.580784,1.000212
1777,2016-01-01 07:46:59.285,0.010749,0.703602,0.680271,46.580784,1.000192
1778,2016-01-01 07:46:59.445,0.023453,0.715329,0.688577,46.580784,1.000165
1779,2016-01-01 07:46:59.646,0.006352,0.702625,0.693463,46.580784,1.000155
1780,2016-01-01 07:46:59.768,0.024919,0.688455,0.679782,46.580784,1.000154
1781,2016-01-01 07:47:00.079,0.018079,0.696762,0.680759,46.580784,1.000120
1782,2016-01-01 07:47:00.145,0.030294,0.729010,0.692975,46.580784,1.000093
1783,2016-01-01 07:47:00.248,0.008795,0.716795,0.695418,46.580784,1.000101
1784,2016-01-01 07:47:00.409,0.012215,0.729499,0.683203,46.580784,1.000098
1785,2016-01-01 07:47:00.571,0.025896,0.708488,0.658283,46.580784,1.000112
1786,2016-01-01 07:47:00.729,0.019056,0.723635,0.689066,46.580784,1.000067

## Colors for Each Acitivity

In [16]:
ts_ = []
labels = []

basepath = '/content/gdrive/My Drive/coding/Senior Project/'

with open(timepath + 'times_' + subject_name + '.txt','r') as f:
    for line in f:
        t = line.strip('\n').split('\t')
        ts_.append(float(t[0]))
        labels.append(t[1])

accum = 0
ts = []
for x in ts_:
    accum += x
    ts.append(round(accum,2))

lb_set = set()
for x in labels:
    lb_set.add(x)

lb_ = list(lb_set)

set_cnt = []
for i in range(len(lb_)):
    set_cnt.append(0)

lb = []
lb.append('NaN')

for x in labels:
    for i in range(len(lb_)):
        if(lb_[i]==x and set_cnt[i]!=1 and lb_[i]!='NaN'):
            set_cnt[i] = 1
            lb.append(x)

colors = ['#808080', '#E6194B', '#3CB44B', '#FFE119', '#4363D8', '#F58231',
          '#911EB4', '#46F0F0', '#F032E6', '#BCF60C', '#008080', '#E6BEFF', 
          '#9A6324', '#800000', '#AAFFC3', '#808000', '#000075']

color_dict = {}
for i in range(len(lb)):
    color_dict[lb[i]] = colors[i]
    
print(color_dict)

lb_color = []
for x in labels:
    lb_color.append(color_dict[x])

print(lb_color)
print(len(lb_color))
print(ts)

NameError: name 'timepath' is not defined

## Plot Acc, AI with Colors

In [ ]:
dict1 = df1.to_dict(orient='list')

fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(16,12))
fig.tight_layout()

ts_cnt = 0
x_axis = []
y_ai = []

ax = axes[0]
ax.plot(dict1['x'],color='r',label='X')
ax.plot(dict1['y'],color='g',label='Y')
ax.plot(dict1['z'],color='b',label='Z')
ax.legend(loc='upper right')
ax.set_title('X,Y,Z')

ax = axes[1]
for i in range(len(dict1['timestamp'])):
    if(dict1['AI'][i]>0):
        if(calc_sec(dict1['timestamp'][i].split(' ')[1])>calc_sec(start_time)+ts[ts_cnt]):
            ax.plot(x_axis,y_ai,color=lb_color[ts_cnt])
            ts_cnt += 1
            x_axis = []
            y_ai = []
            
        elif(ts_cnt==len(lb_color)-1):
            ax.plot(x_axis,y_ai,color=lb_color[ts_cnt])
            
        x_axis.append(i)
        y_ai.append(dict1['AI'][i])

ax.set_title('Activity Index')

# ax = axes[2]
# ax.plot(dict1['HR'],label='HR')
# ax.set_ylim(bottom=30,top=110)
# ax.legend(loc='upper right')
# ax.set_title('Heart Rate')


plt.figure(figsize=(15,20))
fig.savefig(basepath + 'Graphs/testrun_' + subject_name + '.png', dpi = 300)

plt.show()

## Calculate Roll, Pitch, Yaw Angles

In [ ]:
import math

In [ ]:
ax = np.array(dict1['x'])
ay = np.array(dict1['y'])
az = np.array(dict1['z'])

pitch = 180 * np.arctan(ax/np.sqrt(ay*ay + az*az))/math.pi
roll = 180 * np.arctan(ay/np.sqrt(ax*ax + az*az))/math.pi
yaw = 180 * np.arctan(az/np.sqrt(ax*ax + ay*ay))/math.pi

plt.figure(figsize=(16,6))
plt.plot(pitch,color='r',label='pitch')
plt.plot(roll,color='g',label='roll')
plt.plot(yaw,color='b',label='yaw')
plt.legend()

plt.show()

## Classify Walking Periods

In [ ]:
def fluc(axis,rs,rf,diff=0.15):
    cnt = 0
    mult = 0
    j = 1

    i = rs
    while(i<rf):
        if(abs(df1[axis][i+j]-df1[axis][i])>diff):
            if(cnt==0):
                if(df1[axis][i+j]>df1[axis][i]):
                    mult = 1
                else:
                    mult = -1
                cnt += 1
            else:
                if((df1[axis][i+j]>df1[axis][i] and mult==-1) or 
                   (df1[axis][i+j]<df1[axis][i] and mult==1)):
                    mult *= -1
                    cnt += 1
            i += j-1  
        else:
            if(cnt==0):
                if(df1[axis][i+j]>df1[axis][i]):
                    mult = 1
                else:
                    mult = -1
        i += 1

    return cnt

In [ ]:
step = 10
s = 0
f = len(df1)

thres = 2

walk = [set()]
arr = [[]]
ax = ['x']
axes = 1

for i in range(s,f,step):
    for j in range(axes):
        if(i+step<f):
            arr[j].append(fluc(ax[j],i,i+step,diff=0.15))
        else:
            arr[j].append(fluc(ax[j],i,f-1,diff=0.15))
        if(len(arr[j])>=6 and 
           arr[j][-6]>=thres and arr[j][-5]>=thres and 
           arr[j][-4]>=thres and arr[j][-3]>=thres and 
           arr[j][-2]>=thres and arr[j][-1]>=thres):
            for k in range(6):
                walk[j].add(i-k*step)
        
for i in range(axes):
    walk[i] = list(walk[i])
    walk[i] = sorted(walk[i])

In [ ]:
walk_its = walk[0]

print(walk_its)

In [ ]:
class period:
    def __init__(self,s,f):
        self.s = s
        self.f = f

In [ ]:
walk_its_p = []
kp = walk_its[0]

for i in range(len(walk_its)):
    if(i+1<=len(walk_its)-1 and walk_its[i+1]-walk_its[i]>step):
        walk_its_p.append(period(kp,walk_its[i]))
        kp = walk_its[i+1]

    if(i==len(walk_its)-1 and walk_its[i]-walk_its[i-1]==step):
        walk_its_p.append(period(kp,walk_its[i]))

for x in walk_its_p:
    print(x.s,x.f)

## Classifying Inactive Periods

In [ ]:
print(np.std(ai1[550:625]))

In [ ]:
ki = -1
kj = -1
s = []
sd_thres = 0.002

for i in tqdm(range(0,len(ai1)-1)):
    if(not(len(s)!=0 and s[-1].s==ki and s[-1].f==kj)):
        s.append(period(ki,kj))
    for j in range(1,len(ai1)):
        if(j-i>=50):
            if(np.std(ai1[i:j])<sd_thres):
                kj = j
                ki = i

In [ ]:
seq = []
for i in range(len(ai1)):
    seq.append(i)
    
sequence = []
for x in s:
    if(x.s in seq and x.f in seq):
        for i in range(x.s,x.f+1):
            seq.remove(i)
        sequence.append(x)

for x in sequence:
    print(x.s,x.f)

## Plot the Classified Activity Index

In [ ]:
x_axis = []
y_axis = []
active = set()
seq_idx = 0
idx = 1 + np.std(ai1)

fig = plt.figure(figsize=(16,6))

for i in range(len(ai1)):
    if(seq_idx<len(sequence) and i>=sequence[seq_idx].s and i<=sequence[seq_idx].f):
#         print('r',i)
        x_axis.append(i)
        y_axis.append(ai1[i])
        active.add(ai1[i])
    
    if(seq_idx<len(sequence) and i==sequence[seq_idx].f):
        plt.plot(x_axis,y_axis,color='r')
        x_axis = []
        y_axis = []
        seq_idx += 1
        
    if(seq_idx<len(sequence) and i<=sequence[seq_idx].s):
#         print('b++',i)
        x_axis.append(i)
        y_axis.append(ai1[i])
    
    if(seq_idx<len(sequence) and i==sequence[seq_idx].s):
        plt.plot(x_axis,y_axis,color='b')
        x_axis = []
        y_axis = []
    
    
x_axis = []
y_axis = []

p_idx = 0
for i in range(len(df1)):
    if(p_idx<len(walk_its_p)):
        if(i>=walk_its_p[p_idx].s and i<=walk_its_p[p_idx].f):
    #         print('r',i)
            x_axis.append(i)
            y_axis.append(ai1[i])

        if(i==walk_its_p[p_idx].f):
            plt.plot(x_axis,y_axis,color='b')
            x_axis = []
            y_axis = []
            p_idx += 1

    if(p_idx<len(walk_its_p)):
        if(i<=walk_its_p[p_idx].s):
    #         print('b++',i)
            x_axis.append(i)
            y_axis.append(ai1[i])

        if(i==walk_its_p[p_idx].s):
            x_axis = []
            y_axis = []
            
    else:
        x_axis.append(i)
        y_axis.append(ai1[i])
        if(i==len(df1)-1):
            plt.plot(x_axis,y_axis,color='r')

fig.savefig(basepath + 'Graphs/' + subject_name + '.png', dpi=300)          
plt.show()

In [ ]:
x_axis = []
y_axis = []

p_idx = 0

fig = plt.figure(figsize=(16,6))

print(len(walk_its_p))
for i in range(len(df1)):
    if(p_idx<len(walk_its_p)):
        if(i>=walk_its_p[p_idx].s and i<=walk_its_p[p_idx].f):
    #         print('r',i)
            x_axis.append(i)
            y_axis.append(ai1[i])

        if(i==walk_its_p[p_idx].f):
            plt.plot(x_axis,y_axis,color='r')
            x_axis = []
            y_axis = []
            p_idx += 1

    if(p_idx<len(walk_its_p)):
        if(i<=walk_its_p[p_idx].s):
    #         print('b++',i)
            x_axis.append(i)
            y_axis.append(ai1[i])

        if(i==walk_its_p[p_idx].s):
            plt.plot(x_axis,y_axis,color='b')
            x_axis = []
            y_axis = []
            
    else:
        x_axis.append(i)
        y_axis.append(ai1[i])
        if(i==len(df1)-1):
            plt.plot(x_axis,y_axis,color='b')
    
fig.savefig(subject_name + '_walking.png')
plt.show()

## Fourier Transform

In [ ]:
a1 = np.array(ai1)
N = a1.shape[0]

T = 0.16
x_ = np.linspace(1/(T*(N-1)), 1/(2*T), (N+1)//2-1)
# x = np.linspace(1/(T*(N-1)), 1/T, N-1)

ft = np.fft.rfft(a1)

# print(ft)
print(ft.shape)
print(x_.shape)

In [ ]:
fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(16,12))

ax = axes[0]
ax.plot(a1)
ax.set_title('Activity Index')

ax = axes[1]
ax.plot(x_,np.abs(ft)[1:],color='r')
ax.set_ylim(bottom=-1)
ax.set_title('Amplitude')

# ax = axes[2]
# ax.plot(x,ft.imag[1:],'b')
# ax.set_title('Imaginary Part')

plt.show()
# fig.savefig('testrun_ped_fft.png',dpi=300)

In [ ]:
f = 0.3
r = int(N*T*f)

mask = np.zeros((N+1)//2)
mask[0:r+1] = 1
# mask[r:] = 1
print(r)

y_masked = np.fft.irfft(ft*mask)

plt.figure(figsize=(16,6))
plt.plot(np.abs(y_masked))
plt.show()

In [ ]:
f1 = 0.3
f2 = 2.5

lo_mask = np.where(x_>f1)
med_mask = np.where((x_-f1)*(x_-f2)>=0)
hi_mask = np.where(x_<f2)

pos_mask = lo_mask

med_freq_fft = ft.copy()
med_freq_fft[pos_mask] = 0
filtered_sig = np.fft.irfft(med_freq_fft)

plt.figure(figsize=(16,6))
plt.plot(np.abs(filtered_sig))
plt.show()

# plt.savefig('mask_lowpass.png',dpi=300)